### ISSUE TITLE
MacOS error  .Fsed: 1: "./bobsrepo.I ...": invalid command code .

### ISSUE THREAD

**Issue by ghost** [ReSearchITEng/github-active-repo-finder#1]
Great work on this project!
 I could only get page 1 of the results, then I'd get the error message in the title. The issue is the MacOS version of sed. To solve this issue 
1. brew install gnu-sed
2. go into the python file and replace sed with gsed

Problem solved!
Hope this helps

**Comment by ReSearchITEng** [comment]
Wow, I did not  expect anyone else would spend the time to understand what it does and how to use it.
Thanks for the tip, I've updated the docs.

**Comment by ghost** [comment]
I’ve found it incredibly helpful. My use case is tracking repos that crack Parallels desktop cracks, on Thursday it found forked 600 repos, that would be a nightmare to try to do by hand.
Thanks for sharing your work!
Pat

From: ReSearchITEng ***@***.***>
Date: Saturday, July 8, 2023 at 10:59 AM
To: ReSearchITEng/github-active-repo-finder ***@***.***>
Cc: Pat Ford ***@***.***>, Author ***@***.***>
Subject: Re: [ReSearchITEng/github-active-repo-finder] MacOS error .Fsed: 1: "./bobsrepo.I ...": invalid command code . (Issue #1)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>
CAUTION: This e-mail is from an external sender, do not click on unexpected links or attachments.


Wow, I did not anyone else would spend the time to understand what it does and how to use it.
Thanks for the tip, I've updated the docs.
